# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
groovy = "4.0.29"
spock-core = "2.4-M6-groovy-4.0"

[libraries]
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock-core" }
